-- =========================================================
-- Seed data for the Employee Management System
-- =========================================================
-- Passwords are BCrypt hashes for:  Admin@123 (admin) and User@123 (user)
-- These values are generated by the application's DbSeeder at runtime;
-- this script documents the equivalent data for manual/reference use.
-- =========================================================

-- Demo users (PasswordHash below corresponds to the documented passwords)
INSERT INTO "Users" ("Username", "Email", "PasswordHash", "Role", "CreatedAt") VALUES
('admin', 'admin@ems.com', '$2a$12$REPLACE_WITH_ADMIN_HASH', 'Admin', now()),
('user',  'user@ems.com',  '$2a$12$REPLACE_WITH_USER_HASH',  'User',  now())
ON CONFLICT ("Username") DO NOTHING;

-- Departments
INSERT INTO "Departments" ("DepartmentName", "Description", "CreatedAt") VALUES
('IT', 'Information Technology and Infrastructure', now()),
('Human Resources', 'Recruitment, payroll and employee welfare', now()),
('Finance', 'Accounting, budgeting and financial planning', now()),
('Marketing', 'Branding, campaigns and market research', now()),
('Sales', 'Business development and client acquisition', now())
ON CONFLICT ("DepartmentName") DO NOTHING;

-- Employees (DepartmentId resolved by name at runtime via the EF Core seeder)
-- For manual use, replace the department references accordingly.
